### ISSUE TITLE
Print programmer-friendly stack trace

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/argobots#101]
It is improvement of #12; now `ABT_info_trigger_print_all_thread_stacks` prints raw call stacks. Raw call stacks can be hardly read by humans, so better dumping mechanism (e.g., show the function stack) is favorable. As @bfaccini mentioned in #12, libunwind (https://www.nongnu.org/libunwind/) should be useful.

**Comment by bfaccini** [comment]
Hello, 
trying to implement some debug capability to our software using ABT_info_trigger_print_all_thread_stacks() API, we have found some difficulties due to the current raw format only.
Would be very useful if : 
                   _ the unnecessary print of bunch of zeroes, frequently present/unused on top of stacks, could be somewhat compressed, and more generally all big chunks of zeroes. This will slightly decrease the size of dump, particularly for ABT configurations where there is a huge number of active ULTs.

                  _ since current callback capability is not really useful, ABT_info_trigger_print_all_thread_stacks() callback could also pass a struct/pointer argument where it could get some information about each ULT context (top/bottom pointers of stack), and then use it, why not to unwind, on its own.  

This does not mean that current raw format is useless, because it will also help for more complex debugging where some call-sequence anteriority debug may also be required.

**Comment by shintaro-iwasaki** [comment]
Thank you for your suggestion.  I think the suggested extension is useful (or necessary to make this feature really useful). 
I will take a look at this issue this week. but overall I believe implementing it in Argobots is easier.

The following explains why it is challenging.

### Detailed descriptions:

The current biggest problem is difficulty of obtaining a stack pointer even for the Argobots runtime.  Argobots supports two implementations for user-level threading primitives (`fcontext` and `ucontext`) that use different implementations for every architecture (x86, AMD64, POWER, ARM64, ...).

#### 1. Compression of unused stack regions

We cannot guarantee that the unused memory regions are zero cleared.  Malloc'ed memory might not be zero cleared.  The stack region can be dirty if it has been already used by functions calls invoked previously. It can reduce the overheads, though.

#### 2. Show more useful information (such as top/bottom pointers of stack) in `ABT_info_trigger_print_all_thread_stacks()`

It is hard to get bottom stack pointers even for Argobots (strictly speaking, we can get it but we don't know that pointer is useful for stack unwinding).  This also requires some modification in Argobots.

**Comment by shintaro-iwasaki** [comment]
#246 implements stack unwinding.If one uses libunwind to unwind stacks, it should be really tough with the current Argobots since  constructing libunwind's context is not very easy if one only knows a stack pointer/an instruction pointer.

**Comment by shintaro-iwasaki** [comment]
I believe the current libunwind (#246) covers the best Argobots can do for now. Further improvement (e.g., unwinding a stack of a running ULT) needs very intensive engineering, which is not practical at this point. If you need any improvement of this feature, please create a new issue.
