### ISSUE TITLE
Fibonacci_thread_task example seg faulting for specifc parameters

### ISSUE THREAD

**Issue by pnookala** [pmodels/argobots#103]
This example results in segmentation fault when computing Fib(3) with 1 execution stream. It creates thousands of ULTs ultimately resulting in a segmentation fault at some point. This example seems to always work when there are more than one execution streams and also for other parameters tested.

**Comment by shintaro-iwasaki** [comment]
I believe this issue mentions https://github.com/pmodels/argobots/blob/master/examples/fibonacci_thread_task.c

I haven't investigated the reported bug , but this example violates the rule of the tasklet as pointed out by #15. Specifically, the task (see
https://github.com/pmodels/argobots/blob/master/examples/fibonacci_thread_task.c#L202) calls mutex, which is a blocking operation (see https://github.com/pmodels/argobots/blob/master/examples/fibonacci_thread_task.c#L96). We should remove or fix this example. We also need to find other examples where tasklets call any blocking operations.

**Comment by shintaro-iwasaki** [comment]
This issue was fixed by #164. Thank you for reporting this issue!
