### ISSUE TITLE
Silencing error messages

### ISSUE THREAD

**Issue by mdorier** [pmodels/argobots#112]
Would it be possible to pass a flag at compile time to silence error messages (or better: make Argobots by default not print error messages and have a flag to enable them)? Namely this would mean redefiniting `HANDLE_ERROR_FUNC_WITH_CODE` in `abti_error.h` conditionally to whether the user requested error messages.

In some code that uses Argobots, we call `ABT_xstream_set_main_sched`. Right now the call will fail if the pool associated with the ES has work units in it. In our code that's totally fine and we just ignore the error code, but there is still the error message polluting our standard error.

**Comment by shintaro-iwasaki** [comment]
You're right. If an error is expected and handled by a user program, the current error message is annoying. However, right now there is no way to make it silent.

I want to support this (planning to extend `--enable-debug`). If you can wait for a while, I will work on it, but I always welcome if you would make a PR.

**Comment by mdorier** [comment]
Done: https://github.com/pmodels/argobots/pull/113

**Comment by shintaro-iwasaki** [comment]
I merged #113.
Thanks a lot!
