### ISSUE TITLE
no checks for malloc success in valgrind support code

### ISSUE THREAD

**Issue by jolivier23** [pmodels/argobots#115]
ABTI_valgrind_register_stack does malloc without checking the returned pointer.

**Comment by shintaro-iwasaki** [comment]
Thanks. I believe what you mean is that in 
https://github.com/pmodels/argobots/blob/master/src/mem/valgrind.c#L53
```
    ABTI_valgrind_id_list *p_valgrind_id_list =
                 (ABTI_valgrind_id_list *)malloc(sizeof(ABTI_valgrind_id_list));
```
`p_valgrind_id_list` is used without checking if it is NULL (e.g., `ABTI_ASSERT(p_valgrind_id_list);`).

Now Argobots misses this kind of memory check (e.g., https://github.com/pmodels/argobots/blob/master/src/global.c#L70 where `ABTU_malloc` is directly          
replaced by `malloc`). We need to thoroughly check the Argobots code.

**Comment by ashleypittman** [comment]
Looking at this code I wonder if it would be better to add ABTI_valgrind_id directly to the ABTI_thread struct which would avoid the need for a linked list and simply remove the error path in question.

**Comment by ashleypittman** [comment]
> Thanks. I believe what you mean is that in
> https://github.com/pmodels/argobots/blob/master/src/mem/valgrind.c#L53
> 
> ```
>     ABTI_valgrind_id_list *p_valgrind_id_list =
>                  (ABTI_valgrind_id_list *)malloc(sizeof(ABTI_valgrind_id_list));
> ```
> 
> `p_valgrind_id_list` is used without checking if it is NULL (e.g., `ABTI_ASSERT(p_valgrind_id_list);`).

Yes, that is what we were looking at.

> Now Argobots misses this kind of memory check (e.g., https://github.com/pmodels/argobots/blob/master/src/global.c#L70 where `ABTU_malloc` is directly
> replaced by `malloc`). We need to thoroughly check the Argobots code.

A cursory check of the code reveals lack of checking is widespread, although memalign does at least have an assert() to check for failure.  Is there a existing ticket to track this work and what are the plans for checking the code?

**Comment by jolivier23** [comment]
I've filed #116 to track the larger issue.

**Comment by shintaro-iwasaki** [comment]
Adding the `p_valgrind_id_list` part to `ABTI_thread` is a good idea especially to reduce "malloc/free", but it can enlarge the structure size and might increase the memory use (especially if it gets bigger than the multiple of the cache line size). As usually people don't run Argobots on valgrind (extremely slow), the priority of optimization for "--valgrind-enabled" + use of valgrind is low now.

**Comment by shintaro-iwasaki** [comment]
#238 fixes this valgrind issue (Valgrind check ignores thread stacks when `malloc()` fails).
#116 keeps tracking the larger issue.
