### ISSUE TITLE
malloc failures should be checked and assertion should be avoided

### ISSUE THREAD

**Issue by jolivier23** [pmodels/argobots#116]
Malloc can fail normally when there is memory pressure.   There may be situations where it is appropriate to exit the application but in many cases garbage collection or other techniques can be used to free memory and recover appropriately.  In our project (DAOS), we generally want to return an error code to the client in such situations and we want the opportunity to take steps in the server (where we use argobots) to reduce memory consumption and avoid future malloc failures at runtime rather than killing the server as the latter is a very expensive operation in a fault tolerant storage system.

This ticket is a feature request to return error codes on out-of-memory situations, at least at the API level so that users of the argobots library can choose whether to attempt to free up memory and try to recover or to give up and crash.  This is related to ticket #115 but not specific to just the valgrind code path so adding as a new ticket

**Comment by shintaro-iwasaki** [comment]
Resource allocation failures in the current Argobots is reasonably, though not thoroughly (e.g., by using formal verification techniques), tested. Argobots functions return an error properly after freeing resources already allocated. The new tests introduced by #309 check error handling paths by mocking system allocation functions (`malloc()`, `mmap()`, `pthread_create()`, and so on).

Please open an issue if you find any issue.
