### ISSUE TITLE
memory leak in ABT_init

### ISSUE THREAD

**Issue by jolivier23** [pmodels/argobots#119]
If I run the following code under valgrind with --leak-check=full I get a memory leak
int main(int argc, char **argv)
{
	ABT_init(0, NULL);
	ABT_finalize();
	return 0;
}

Here is the call stack for the reported leak.   It doesn't appear to be freeing all memory allocated for main xstream.

==8020== 40 bytes in 1 blocks are definitely lost in loss record 1 of 1
==8020==    at 0x483880B: malloc (vg_replace_malloc.c:309)
==8020==    by 0x485908D: ABTI_elem_create_from_xstream (in /home/jvolivie/prebuilt/argobots/lib/libabt.so.0.0.0)
==8020==    by 0x4852D15: ABTI_xstream_create (in /home/jvolivie/prebuilt/argobots/lib/libabt.so.0.0.0)
==8020==    by 0x4852EAA: ABTI_xstream_create_primary (in /home/jvolivie/prebuilt/argobots/lib/libabt.so.0.0.0)
==8020==    by 0x484DF7E: ABT_init (in /home/jvolivie/prebuilt/argobots/lib/libabt.so.0.0.0)
==8020==    by 0x401153: main (in /home/jvolivie/daos/a.out)

**Comment by shintaro-iwasaki** [comment]
Thank you for reporting a bug. It seems that the bug reported by #6 has not been fixed yet.
I will look into it and hopefully make a patch within 24 hours.

**Comment by shintaro-iwasaki** [comment]
It was fixed by #120.
