### ISSUE TITLE
ABT_xstream_start should be able to revive a joined ES

### ISSUE THREAD

**Issue by mdorier** [pmodels/argobots#146]
Right now a joined ES cannot be revived. It would be useful to be able to revive by calling ABT_xstream_start.

**Comment by shintaro-iwasaki** [comment]
I agree. It should be useful.

I'm working on it to implement `ABT_xstream_revive()`. It requires some changes (#147 and a few PRs) in the current xstream code, so please wait a few days.

**Comment by shintaro-iwasaki** [comment]
#150 was merged. Thank you for suggesting this feature!
