### ISSUE TITLE
Power8 build fails due to ABT_CONFIG_USE_FCONTEXT being unset

### ISSUE THREAD

**Issue by jgmoore-or** [pmodels/argobots#18]
Same error as in issue #11:

(make produces)

 CC       libabt_la-barrier.lo
In file included from ../src/include/abtd.h:48:0,
                 from ../src/include/abti.h:128,
                 from barrier.c:6:
../src/include/abtd_thread.h: In function 'ABTD_thread_context_set_arg':
../src/include/abtd_thread.h:162:2: error: #error "Not implemented yet"
 #error "Not implemented yet"

My configure command line is:
./configure CC=gcc
but same error occurs if default (xlc) compiler is used.

**Comment by halimamer** [comment]
@jgmoore-or , thank you for reporting the problem.
The intention of the current code is to support primary fcontext (from Boost) for user-space context switching and a fallback path, ucontext (system provided), when fcontext is unavailable.
Support for ucontext, however, is broken at the moment and we are working on fixing it

**Comment by halimamer** [comment]
@jgmoore-or, we found that our architecture detection code misinterpreted Power8 as a non-PPC64 architecture. A PR that fixes this and thus allows `fcontext` to run on Power8 is under review. Meanwhile, you could try that PR #20 to get you moving
