### ISSUE TITLE
synchronization: guarantee that a ULT does not yield if no contention 

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/argobots#287]
This issue is raised by @carns. https://lists.argobots.org/pipermail/discuss/2021-January/000094.html

We need to examine the implementation, but in any case the Argobots specification should guarantee that a ULT that locks/unlocks asynchronization object may not spuriously yield if there is no contention (e.g., `mutex`) and otherwise explicitly stated. At least I implemented so as a developer, but this behavior should be clarified and tested. Maybe there are some bugs.

**Comment by carns** [comment]
Just to follow up on the github issue: the only instance I have observed where this guarantee does not hold is on a power9 CPU with Argobots 1.0.  It works as expected now with origin/main.
