### ISSUE TITLE
Compile error on gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

### ISSUE THREAD

**Issue by hyoklee** [pmodels/argobots#289]
In **src/sched/config.c** , `for (int i = 0; i < ABTI_SCHED_CONFIG_HTABLE_SIZE; i++)` causes the error.

**Comment by shintaro-iwasaki** [comment]
@hyoklee Thank you very much for your comment! Yes I introduced that mistake.

I would truly appreciate it if you could create a PR. I'd be happy if the commit message is `sched_config: close pmodels#289`.
