### ISSUE TITLE
Fix the protocol to when freeing pools

### ISSUE THREAD

**Issue by halimamer** [pmodels/argobots#30]
Currently,  if you try to free manually a pool after it got freed automatically then you would 1) either get an error message if error checking is enabled or 2) fall into a double free corruption situation. This needs either clarified in the specification or fixed in the code by checking the pool against ABT_POLL_NULL and allow this case to return without an error or check the "automatic" field and forbid manually freeing it.

**Comment by shintaro-iwasaki** [comment]
The new specification (#282) clarified this behavior (though this protocol remains confusing). I will close this issue.
