### ISSUE TITLE
Export an API to get thread func address from ABT_unit

### ISSUE THREAD

**Issue by NiuYawei** [pmodels/argobots#314]
Now we are trying to implement a watchdog in our customized scheduler to detect if any ABT_unit runs unexpected long: If a ABT_unit takes too long (preventing scheduler from scheduling next ABT_unit), we'll log an error message with the thread/task function address & symbol provided, so that developer would be able to tell which thread doesn't yield voluntarily or blocks the whole xstream somehow (like an unexpected sys call, etc.)

Current problem is that there isn't an easy way to get the function address from ABT_unit, I'm wondering if such an API could be exported from Argobots to get the function address from ABT_unit? I think that'll be very helpful for development/debugging.

**Comment by shintaro-iwasaki** [comment]
Thank you for your comment.  Now Argobots does not have a function that returns a function pointer of `ABT_thread` or `ABT_unit`.
You can always store extra data in ULT's TLS (`ABT_thread_set_specific()`), but I don't think it is straightforward.

Regarding API, would something like the following functions work for your case?
```c
int ABT_unit_get_thread(ABT_unit unit, ABT_thread *thread);
int ABT_thread_get_thread_func(ABT_thread thread, void (**thread_func)(void *));

// ABT_unit is for "scheduling" so an API that directly gets a function pointer from ABT_unit is a bit weird.
```

Implementing them is easy.  If these functions above suffice, the Argobots 1.1 release, which is planned to be released around the end of March, can include this.  If so, Argobots 1.1rc2 will be created before the release.

(If this functionality is not urgent, we'd like to delay its implementation after Argobots 1.1).

**Comment by NiuYawei** [comment]
Yes, that's sufficient for us.

It's not that urgent, you could pick the proper release to have them according to your release schedule. Thanks a lot.

**Comment by shintaro-iwasaki** [comment]
Thanks for your suggestion. #319 added those functions. Argobots 1.1 will include these functions.

Please open a new issue if any new functions are needed.
