### ISSUE TITLE
Test fails on my laptop.

### ISSUE THREAD

**Issue by shintaro-iwasaki** [pmodels/argobots#34]
The test sometimes fails when I execute it on my laptop.
```
$ make check
...
PASS: sched_user_ws
PASS: pool_access
PASS: mutex
PASS: mutex_prio
FAIL: mutex_recursive
...
```
Specifically, it shows the following error nondeterministically:
```
$ ./mutex_recursive
lt-mutex_recursive: mutex.c:656: ABTI_mutex_wait: Assertion `rank < p_htable->num_rows' failed.
Aborted
```

It seems because my laptop has few cores.
The following seems happening.
1. `p_global->num_cores` is set to the number of cores.
https://github.com/pmodels/argobots/blob/master/src/arch/abtd_env.c#L29
2.  `p_global->max_xstreams` is (by default) set to `p_global->num_cores`.
https://github.com/pmodels/argobots/blob/master/src/arch/abtd_env.c#L82
3. `p_global->max_xstreams` is used in mutex, so this mutex can deal with at maximum the total number of cores.
https://github.com/pmodels/argobots/blob/master/src/include/abti_mutex.h#L95
4. However, test uses 4 xstreams.
https://github.com/pmodels/argobots/blob/master/test/basic/mutex_recursive.c#L11

My laptop only has 2 cores, so this benchmark sometime fails.

**Comment by carns** [comment]
Anecdotally I've hit this assertion before too (I don't have a test case handy, I was working on something else at the time and didn't have time to investigate.  I can probably find it again if needed though).

Regardless of the test script settings, in general should this condition cause an assertion?  

I have some use cases where it is helpful to oversubscribe cores because I expect some execution streams to be blocked on system calls to I/O devices, and I need more I/O concurrency than I have cores available.

**Comment by shintaro-iwasaki** [comment]
In general, users should not observe this assertion. This assertion should happen because of this problem.

I agree on the usefulness of oversubscribing cores, but the current Argobots uses by default the number of cores (observed by OS) as ``p_global->num_cores``. 

The workaround is setting an environmental variable (``ABT_MAX_NUM_XSTREAMS``) outside the program, or setting it inside the program before ``ABT_init()`` (e.g., use ``putenv``, see #35 ).

I come up with a few options to address this problem in future.
1. Change the mechanism of ``thread_htable`` so that it does not rely on ``p_global->num_cores``. Argobots must be changed.
2. Provide a function to set ``p_global->num_cores``. Argobots and user programs must be changed.

**Comment by carns** [comment]
Thanks for the putenv() tip @shintaro-iwasaki.  I'll see if I can narrow down the assertion that I was hitting and report back.  I'm fine setting an extra parameter for my workload, as long as I don't get a cryptic assertion if I forget :)

**Comment by shintaro-iwasaki** [comment]
PR #35 was merged.

**Comment by shintaro-iwasaki** [comment]
Several users report this problem. Since the current workaround (predicting the maximum number of execution streams and setting `ABT_MAX_NUM_XSTREAMS` before `ABT_Init`) is not always feasible, the best way to address this issue is making `ABT_mutex` independent of `p_global->max_xstreams`. Otherwise, the runtime at least shows more useful information so that users can set a proper `ABT_MAX_NUM_XSTREAMS`.

**Comment by carns** [comment]
I just hit this assertion on my laptop again today.  Unfortunately I had forgotten about this ticket and thought it was a bug in my code for a while until I found this issue on github again :)

The use case was an experiment on my laptop where I expected execution streams to be largely blocked on Linux system calls and had thus deliberately over-subscribed my laptop (which only has 2 cores) to test it.  The execution streams needed to coordinate occasional updates to a shared data structure and were thus sharing a mutex.

I would like for Argobots to gracefully allow mutexes with more participants than there are cores.  As an interim solution it would have saved me some time and frustration if there were a helpful error message (e.g., identifying the problem at ES creation time and displaying "Error: attempting to create 3 ESes while system has only 2 cores; please increase ABT_MAX_NUM_XSTREAMS environment variable prior to ABT_Init()")

**Comment by shintaro-iwasaki** [comment]
Thanks. I admit this behavior is very annoying.
I will raise the priority of this problem. Please give me a few weeks.

**Comment by shintaro-iwasaki** [comment]
Sorry for the long delay to merge PRs.

Right now Argobots has two mechanisms to avoid the mutex-related issue:
1. By default enable a mutex algorithm that does not take `ABT_MAX_NUM_XSTREAMS`.
2. (Even if 1 is disabled manually at configuration time) print a warning if an execution stream is created more than the number of `ABT_MAX_NUM_XSTREAMS`. 

Right now with the default configuration, no algorithm in Argobots uses `ABT_MAX_NUM_XSTREAMS`. Let's reopen this issue if another problem is found.
