### ISSUE TITLE
autoconf 128 CAS test fails unless configure is executed from within source tree

### ISSUE THREAD

**Issue by carns** [pmodels/argobots#370]
To reproduce, run configure (on a modern system) the following two ways and compare the contents of `src/include/abt_config.h`:

```
carns-x1-7g ~/w/s/mochi> cd argobots
carns-x1-7g ~/w/s/m/argobots (main=)> mkdir build
carns-x1-7g ~/w/s/m/argobots (main=)> cd build
carns-x1-7g ~/w/s/m/a/build (main=)> ../configure > /dev/null
carns-x1-7g ~/w/s/m/a/build (main=)> cd ../
carns-x1-7g ~/w/s/m/argobots (main=)> ./configure > /dev/null
carns-x1-7g ~/w/s/m/argobots (main=)> 
diff src/include/abt_config.h build/src/include/abt_config.h 
69c69
< #define ABT_CONFIG_HAVE_ATOMIC_INT128 1
---
> /* #undef ABT_CONFIG_HAVE_ATOMIC_INT128 */
```
The problem is the presence of a relative (to the source tree) include path in the autoconf test at https://github.com/pmodels/argobots/blob/main/configure.ac#L1111.

The "out-of-tree" configure/build style is the more prevalent approach in many packaging environments (I assume including Spack, though I haven't confirmed yet).  This is possibly affecting code paths like that described in #369 .

I just wanted to open an issue to document it for the moment; I think I can contribute a PR to fix it in the next couple of days and report if it changes the behavior of #369 or not.

**Comment by carns** [comment]
Minor update to comments above: I just double-checked what spack does at build time, and it actually does an in-tree configure and build in the spack staging directory.  So our spack builds *have* been correctly enabling the 128 bit CAS in Argobots (including on Cooley and my laptop in the #369 issue).  So this issue still needs to be corrected for general usage, but it's not impacting the specific behavior seen in that other issue.

**Comment by shintaro-iwasaki** [comment]
Thanks @carns for the bug report as well as your updates.

> I just wanted to open an issue to document it for the moment; I think I can contribute a PR to fix it in the next couple of days and report if it changes the behavior of #369 or not.

We'd really appreciate your contributions, but we'd also be happy to fix this issue especially if it's not relevant to #369.
If there's no PR from you within this week, I will create a PR to fix this bug (early next week).
