### ISSUE TITLE
Enhancements to ULTs stacks dumps

### ISSUE THREAD

**Issue by bfaccini** [pmodels/argobots#372]
Presently, there is no tag to indicate when ULTs stacks dump has completed, when this is difficult to determine as this process occurs asynchronously.

Also, the raw stack dump do not pack the full zeroes parts, which sometimes causes tons of unnecessary lines of zeroes to be printed.

The following changes should do the trick : 
```
diff --git a/src/info.c b/src/info.c
index cb2c3c7..fabba29 100644
--- a/src/info.c
+++ b/src/info.c
@@ -1373,10 +1373,20 @@ ABTU_ret_err static int print_all_thread_stacks(ABTI_global *p_global, FILE *fp)
     size_t i;
     int abt_errno;
     struct info_pool_set_t pool_set;
+    struct tm *tm = NULL;
+    time_t seconds;
 
     abt_errno = info_initialize_pool_set(&pool_set);
     ABTI_CHECK_ERROR(abt_errno);
     ABTI_xstream *p_xstream = p_global->p_xstream_head;
+
+    seconds = (time_t)ABT_get_wtime();
+    tm = localtime(&seconds);
+    ABTI_ASSERT(tm != NULL);
+    fprintf(fp, "Start of ULT stacks dump %04d/%02d/%02d-%02d:%02d:%02d\n",
+           tm->tm_year + 1900, tm->tm_mon + 1, tm->tm_mday, tm->tm_hour,
+           tm->tm_min, tm->tm_sec);
+
     while (p_xstream) {
         ABTI_sched *p_main_sched = p_xstream->p_main_sched;
         fprintf(fp, "= xstream[%d] (%p) =\n", p_xstream->rank,
@@ -1404,6 +1414,14 @@ ABTU_ret_err static int print_all_thread_stacks(ABTI_global *p_global, FILE *fp)
         if (abt_errno != ABT_SUCCESS)
             fprintf(fp, "  Failed to print (errno = %d).\n", abt_errno);
     }
+
+    seconds = (time_t)ABT_get_wtime();
+    tm = localtime(&seconds);
+    ABTI_ASSERT(tm != NULL);
+    fprintf(fp, "End of ULT stacks dump %04d/%02d/%02d-%02d:%02d:%02d\n",
+           tm->tm_year + 1900, tm->tm_mon + 1, tm->tm_mday, tm->tm_hour,
+           tm->tm_min, tm->tm_sec);
+
     info_finalize_pool_set(&pool_set);
     return ABT_SUCCESS;
 }
diff --git a/src/ythread.c b/src/ythread.c
index 849e948..c4f1e14 100644
--- a/src/ythread.c
+++ b/src/ythread.c
@@ -274,6 +274,8 @@ ABTU_no_sanitize_address void ABTI_ythread_print_stack(ABTI_global *p_global,
         char buffer[32];
         const size_t value_width = 8;
         const int num_bytes = sizeof(buffer);
+        static const char zero[sizeof(buffer)];
+        ABT_bool full_zeroes = ABT_FALSE, multi_lines = ABT_FALSE;
 
         for (i = 0; i < stacksize; i += num_bytes) {
             if (stacksize >= i + num_bytes) {
@@ -282,6 +284,23 @@ ABTU_no_sanitize_address void ABTI_ythread_print_stack(ABTI_global *p_global,
                 memset(buffer, 0, num_bytes);
                 memcpy(buffer, &((uint8_t *)p_stack)[i], stacksize - i);
             }
+
+            /* pack full lines of zeroes */
+            if (!memcmp(zero, buffer, sizeof(buffer))) {
+                if (!full_zeroes) {
+                    full_zeroes = ABT_TRUE;
+                } else {
+                    multi_lines = ABT_TRUE;
+                    continue;
+                }
+            } else {
+                full_zeroes = ABT_FALSE;
+                if (multi_lines) {
+                    fprintf(p_os, "*\n");
+                    multi_lines = ABT_FALSE;
+                }
+            }
+
             /* Print the stack address */
 #if SIZEOF_VOID_P == 8
             fprintf(p_os, "%016" PRIxPTR ":",
```

**Comment by bfaccini** [comment]
Since I don't know if I am allowed to create a PR, nor I know the rules to be followed, I have only pasted my patch into this issue ...

**Comment by shintaro-iwasaki** [comment]
@bfaccini Thank you very much for creating a patch!  Yes, we'd really appreciate your PR. So please just create a PR. There is no explicit/strict rule, but please follow the convention and good coding practice (I mean, "good" for us).
 - Commit title should be `module: desc (<= 70 chars)`.
   - In your case, it should be like ```info: xxx yyy zzz```
 - Commit message should be wrapped at 80 chars.
 - Clean up the whitespace/indent etc (otherwise clang-format CI will reject it: please check `maint/code-cleanup.sh`)

Your patch looks great to me. Just a few points:
 1. Could you explain why you need "when ULTs stacks dump has completed"? I don't oppose it, but I don't know how this is helpful.
 2. Packing the full zeroes parts would be great to add it if it improves the readability, but please let me note that Argobots (i.e., Argobots memory pool or `malloc()`) does not guarantee unused stack regions are zero cleared.
 3. To review this PR, we'd appreciate it if you could put an example output for those changes.

**Comment by bfaccini** [comment]
Hello Shintaro,
Sorry for the long silence, but I have been fully busy working on critical stuff...
Thanks fr the PR submission rules/hints!
To answer your questions/concerns : 
                 1. `Could you explain why you need "when ULTs stacks dump has completed"? ` , usually we plan to use the feature when something wrong has happen or is running, but then we may want to restart/kill our server, so it is really important to be sure if stacks dumps has completed or still not. It could also be helpful for our CI/tests because we want to automate ULTs stacks dumps upon detection of a wrong/unexpected situation.
                 2. `would be great to add it if it improves the readability`, it does really !
                 2'. `Argobots (i.e., Argobots memory pool or malloc()) does not guarantee unused stack regions are zero cleared`, we plan to use our own/external ULTs stacks management.
                 3. `you could put an example output for those changes` , will do.

**Comment by bfaccini** [comment]
[start+end-markers_and_0s-packed_ULT_stacks_dump.txt](https://github.com/pmodels/argobots/files/7929075/start%2Bend-markers_and_0s-packed_ULT_stacks_dump.txt)
Here is an example of an ULT stacks dump, with the start/end markers and raw stacks dump with zeroes packed generated by my patch.

**Comment by bfaccini** [comment]
[PR-374](https://github.com/pmodels/argobots/pull/374) has been created to push the proposed patch/changes above.

**Comment by shintaro-iwasaki** [comment]
@bfaccini Thank you for your PR! I will close this issue.

**Comment by bfaccini** [comment]
Hello Shintaro,
do you know already which Argobots version will start to integrate changes from [PR-374](https://github.com/pmodels/argobots/pull/374) ?
This is to anticipate the changes it will allow/imply in our own code ;-)
Thanks.
