### ISSUE TITLE
[question] Changing the scheduler of an ES "from the outside"

### ISSUE THREAD

**Issue by mdorier** [pmodels/argobots#384]
About `ABT_xstream_set_main_sched` the documentation says this:

> The caller must be running on the main scheduler of xstream. The caller will be associated with the first pool of the scheduler.

If I wanted to change the scheduler of an xstream "ES2" from another xstream "ES1", one idea would be the following:

```
// this ULT will run in ES2
void change_scheduler(void* args) {
   ABT_xstream_set_main_sched(ES2, ...)
}

// in ES1
ABT_thread ult;
ABT_thread_create_on_xstream(ES2, change_scheduler, (void*)ev, ABT_THREAD_ATTR_NULL, &ult);
ABT_thread_join(ult);
ABT_thread_free(&ult);
```

The problem with this is, if I'm understanding correctly, `ABT_thread_create_on_xstream` will push the ULT into the first pool of ES2, not guarantee that ES2 is the ES that will pick up and run the ULT, right? For instance if the pool is shared by ES1 and ES2, ES1 could be the one that ends up running the ULT.

Is there a way to either change the scheduler of an ES from outside of the ES, or a way to guarantee that a ULT runs in a specific ES?

**Comment by shintaro-iwasaki** [comment]
Thanks for your question!

> The problem with this is, if I'm understanding correctly, ABT_thread_create_on_xstream will push the ULT into the first pool of ES2, not guarantee that ES2 is the ES that will pick up and run the ULT, right?

Yes, your understanding is correct.

> Is there a way to change the scheduler of an ES from outside of the ES?

It causes race condition, so it is not possible.

> Is there a way to guarantee that a ULT runs in a specific ES?

Argobots does not have a convenient mechanism for this, but I would create a local pool and attach it to each ES.  For example, a ULT pushed to a local pool P1 is guaranteed to be executed by ES1 if only ES1 pop a ULT from P1 (even if ES2 pushes a ULT to P1).

**Comment by mdorier** [comment]
Thanks! The local pool sounds like a good solution.
