### ISSUE TITLE
Decouple mutexes and spinlocks

### ISSUE THREAD

**Issue by halimamer** [pmodels/argobots#43]
The Argobots API mixes mutexes and spinlocks on the same lock object type: `ABT_mutex_t`. I thought this might cause misuses and this #36 PR proved it. Threads should not use spinlocks with condition variables like it is done now. I prefer the way POSIX separates between mutexes and spinlocks as different object types. We should do that (`ABT_mutex_t` and `ABT_spinlock_t` ) and only pass `ABT_mutex_t` to condition variables. This should deprecate `ABT_mutex_spinlock()` at the same time.

**Comment by shintaro-iwasaki** [comment]
After consideration, we decided that all the Argobots synchronization objects should support both ULTs and tasklets (as well as external threads). I believe it is okay to provide both functionalities via `ABT_mutex`. In any case, the user needs to be responsible for correct scheduling.
