### ISSUE TITLE
get_cur_time() in cond.c duplicates ABT_get_wtime() 

### ISSUE THREAD

**Issue by carns** [pmodels/argobots#51]
Minor issue, but it looks like the get_cur_time() code in cond.c could be replaced with ABT_get_wtime().  There is some code duplication but they are not in sync.  The former lacks an ifdef to handle the HAVE_MACH_ABSOLUTE_TIME configuration option.

**Comment by halimamer** [comment]
the important difference is that `get_cur_time()` is `static inline`. The right fix should make the `ABTD_xxxtime` routines `static inline` then use them without performance loss. We found other internal routines that show up on the critical path but are not `inlined`. We will create a list to track them and remove them once inlining is done

**Comment by halimamer** [comment]
I do agree that on Mac OS, it's a functional bug rather than a performance bug and we should fix it soon

**Comment by shintaro-iwasaki** [comment]
Fix this issue by #123. `get_cur_time()` is replaced by an inline function, `ABTI_get_wtime()`.
